export const IPC_CHANNELS = {
  PING: 'app:ping',
  APP_QUIT: 'app:quit',
  APP_GET_ABOUT: 'app:get_about',
  APP_OPEN_EXTERNAL: 'app:open_external',
  WINDOW_MINIMIZE: 'window:minimize',
  WINDOW_MAXIMIZE_TOGGLE: 'window:maximize_toggle',
  WINDOW_CLOSE: 'window:close',
  WINDOW_IS_MAXIMIZED: 'window:is_maximized',
  CONNECTION_SELECT_FILE: 'connection:select_service_account_file',
  CONNECTION_CONNECT: 'connection:connect',
  CONNECTION_DISCONNECT: 'connection:disconnect',
  CONNECTION_GET_STATUS: 'connection:get_status',
  EXPLORER_LIST_ROOT_COLLECTIONS: 'explorer:list_root_collections',
  EXPLORER_LIST_DOCUMENTS: 'explorer:list_documents',
  EXPLORER_GET_DOCUMENT: 'explorer:get_document',
  EXPLORER_CREATE_DOCUMENT: 'explorer:create_document',
  EXPLORER_UPDATE_DOCUMENT: 'explorer:update_document',
  EXPLORER_DELETE_DOCUMENT: 'explorer:delete_document',
  EXPLORER_LIST_SUBCOLLECTIONS: 'explorer:list_subcollections',
  EXPLORER_DUPLICATE_DOCUMENT: 'explorer:duplicate_document',
  EXPLORER_DUPLICATE_COLLECTION: 'explorer:duplicate_collection',
  QUERY_EXECUTE: 'query:execute',
  QUERY_LIST_SAVED: 'query:list_saved',
  QUERY_SAVE_SAVED: 'query:save_saved',
  QUERY_DELETE_SAVED: 'query:delete_saved',
  BULK_PREVIEW_UPDATE: 'bulk:preview_update',
  BULK_UPDATE_FIELD: 'bulk:update_field',
  BULK_DELETE: 'bulk:delete',
  DATA_TRANSFER_EXPORT_COLLECTION_JSON: 'data_transfer:export_collection_json',
  DATA_TRANSFER_EXPORT_DOCUMENTS_JSON: 'data_transfer:export_documents_json',
  DATA_TRANSFER_EXPORT_DOCUMENTS_CSV: 'data_transfer:export_documents_csv',
  WORKSPACE_GET_STATE: 'workspace:get_state',
  WORKSPACE_ADD_ENTRY: 'workspace:add_entry',
  WORKSPACE_REMOVE_ENTRY: 'workspace:remove_entry',
  WORKSPACE_UPDATE_ENTRY: 'workspace:update_entry',
  WORKSPACE_LOAD_PROJECT: 'workspace:load_project',
  WORKSPACE_UNLOAD_PROJECT: 'workspace:unload_project',
  WORKSPACE_SET_FOCUSED: 'workspace:set_focused'
} as const

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS]
